### PR TITLE
Check for Apple Music Sites, if beta is offline, it switches to official site.

### PR DESCRIPTION
**Pull request by devilAPI**
made this just for fun :)

### CODE REVIEW

**Comment by devilAPI** [comment]
One question, after merging this, yould you please build the application and upload a new release (i really wanna use #14 )

My ram died and im now using 2gb thats why i cant build it myself

**Comment by iiFir3z** [comment]
Yes ill push new builds with the changes shortly.

**Comment by devilAPI** [comment]
oh my goodness i just saw how broken it is im so sorry

**Comment by devilAPI** [comment]
im gonna fix it up asap

**Pull request merged**
